apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-model
  labels:
    app: cost-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-model
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cost-model
    spec:
      restartPolicy: Always
      serviceAccountName: cost-model
      containers:
        - image: ajaytripathy/kubecost-cost-model:latest
          name: cost-model
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "{{prometheusEndpoint}}"  #The endpoint should have the form http://<service-name>.<namespace-name>.svc
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U" # The GCP Pricing API requires a key.
          imagePullPolicy: Always
